import Head from "next/head";
//importing components
import HomePage from "./home";
export default function Home() {
  return (
    <div className="h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
}
