import Head from "next/head";
//importing components
import Nav from "../components/Nav";
import Main from "../components/Main";
export default function Home() {
  return (
    <div className="h-full bg-blue-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Main />
    </div>
  );
}
